// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative pb/NewsPush.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pb/NewsPush.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportantNewsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Placeholder string `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
}

func (x *ImportantNewsRequest) Reset() {
	*x = ImportantNewsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_NewsPush_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportantNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportantNewsRequest) ProtoMessage() {}

func (x *ImportantNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_NewsPush_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportantNewsRequest.ProtoReflect.Descriptor instead.
func (*ImportantNewsRequest) Descriptor() ([]byte, []int) {
	return file_pb_NewsPush_proto_rawDescGZIP(), []int{0}
}

func (x *ImportantNewsRequest) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

type UpdatedNewsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op   string         `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Id   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data *ImportantNews `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdatedNewsResponse) Reset() {
	*x = UpdatedNewsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_NewsPush_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatedNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedNewsResponse) ProtoMessage() {}

func (x *UpdatedNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_NewsPush_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedNewsResponse.ProtoReflect.Descriptor instead.
func (*UpdatedNewsResponse) Descriptor() ([]byte, []int) {
	return file_pb_NewsPush_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatedNewsResponse) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *UpdatedNewsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatedNewsResponse) GetData() *ImportantNews {
	if x != nil {
		return x.Data
	}
	return nil
}

type ImportantNews struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source      int64    `protobuf:"zigzag64,1,opt,name=source,proto3" json:"source,omitempty"`
	Id          string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Title       string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle    string   `protobuf:"bytes,4,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Media       string   `protobuf:"bytes,5,opt,name=media,proto3" json:"media,omitempty"`
	Content     string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	PublishTime int64    `protobuf:"zigzag64,7,opt,name=publishTime,proto3" json:"publishTime,omitempty"`
	Columns     []string `protobuf:"bytes,8,rep,name=columns,proto3" json:"columns,omitempty"`
	Stocks      []*Stock `protobuf:"bytes,9,rep,name=stocks,proto3" json:"stocks,omitempty"`
	TxtType     int64    `protobuf:"zigzag64,10,opt,name=txtType,proto3" json:"txtType,omitempty"`
}

func (x *ImportantNews) Reset() {
	*x = ImportantNews{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_NewsPush_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportantNews) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportantNews) ProtoMessage() {}

func (x *ImportantNews) ProtoReflect() protoreflect.Message {
	mi := &file_pb_NewsPush_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportantNews.ProtoReflect.Descriptor instead.
func (*ImportantNews) Descriptor() ([]byte, []int) {
	return file_pb_NewsPush_proto_rawDescGZIP(), []int{2}
}

func (x *ImportantNews) GetSource() int64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *ImportantNews) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImportantNews) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImportantNews) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *ImportantNews) GetMedia() string {
	if x != nil {
		return x.Media
	}
	return ""
}

func (x *ImportantNews) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ImportantNews) GetPublishTime() int64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

func (x *ImportantNews) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ImportantNews) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

func (x *ImportantNews) GetTxtType() int64 {
	if x != nil {
		return x.TxtType
	}
	return 0
}

type Stock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market string    `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Code   string    `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name   string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tag    *StockTag `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *Stock) Reset() {
	*x = Stock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_NewsPush_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_pb_NewsPush_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_pb_NewsPush_proto_rawDescGZIP(), []int{3}
}

func (x *Stock) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *Stock) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Stock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stock) GetTag() *StockTag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type StockTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight        float64 `protobuf:"fixed64,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Emotion       string  `protobuf:"bytes,2,opt,name=emotion,proto3" json:"emotion,omitempty"`
	EmotionWeight int64   `protobuf:"zigzag64,3,opt,name=emotionWeight,proto3" json:"emotionWeight,omitempty"`
}

func (x *StockTag) Reset() {
	*x = StockTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_NewsPush_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockTag) ProtoMessage() {}

func (x *StockTag) ProtoReflect() protoreflect.Message {
	mi := &file_pb_NewsPush_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockTag.ProtoReflect.Descriptor instead.
func (*StockTag) Descriptor() ([]byte, []int) {
	return file_pb_NewsPush_proto_rawDescGZIP(), []int{4}
}

func (x *StockTag) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *StockTag) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *StockTag) GetEmotionWeight() int64 {
	if x != nil {
		return x.EmotionWeight
	}
	return 0
}

var File_pb_NewsPush_proto protoreflect.FileDescriptor

var file_pb_NewsPush_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x4e, 0x65, 0x77, 0x73, 0x50, 0x75, 0x73, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x38, 0x0a, 0x14, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x61, 0x6e, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x22, 0x5c, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4e, 0x65, 0x77, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x61, 0x6e, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x92, 0x02, 0x0a, 0x0d, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6e, 0x74, 0x4e, 0x65, 0x77,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x12, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x12,
	0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x06, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x52, 0x06, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x78,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x12, 0x52, 0x07, 0x74, 0x78, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x67, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x54, 0x61, 0x67, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x62, 0x0a,
	0x08, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x54, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x65,
	0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x12, 0x52, 0x0d, 0x65, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x32, 0x56, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x73, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x12,
	0x48, 0x0a, 0x11, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6e, 0x74, 0x4e, 0x65, 0x77, 0x73,
	0x50, 0x75, 0x73, 0x68, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x61, 0x6e, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4e, 0x65, 0x77, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x4c, 0x69, 0x73,
	0x74, 0x47, 0x65, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_NewsPush_proto_rawDescOnce sync.Once
	file_pb_NewsPush_proto_rawDescData = file_pb_NewsPush_proto_rawDesc
)

func file_pb_NewsPush_proto_rawDescGZIP() []byte {
	file_pb_NewsPush_proto_rawDescOnce.Do(func() {
		file_pb_NewsPush_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_NewsPush_proto_rawDescData)
	})
	return file_pb_NewsPush_proto_rawDescData
}

var file_pb_NewsPush_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_NewsPush_proto_goTypes = []interface{}{
	(*ImportantNewsRequest)(nil), // 0: pb.ImportantNewsRequest
	(*UpdatedNewsResponse)(nil),  // 1: pb.UpdatedNewsResponse
	(*ImportantNews)(nil),        // 2: pb.ImportantNews
	(*Stock)(nil),                // 3: pb.Stock
	(*StockTag)(nil),             // 4: pb.StockTag
}
var file_pb_NewsPush_proto_depIdxs = []int32{
	2, // 0: pb.UpdatedNewsResponse.data:type_name -> pb.ImportantNews
	3, // 1: pb.ImportantNews.stocks:type_name -> pb.Stock
	4, // 2: pb.Stock.tag:type_name -> pb.StockTag
	0, // 3: pb.NewsPusher.ImportantNewsPush:input_type -> pb.ImportantNewsRequest
	1, // 4: pb.NewsPusher.ImportantNewsPush:output_type -> pb.UpdatedNewsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_NewsPush_proto_init() }
func file_pb_NewsPush_proto_init() {
	if File_pb_NewsPush_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_NewsPush_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportantNewsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_NewsPush_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatedNewsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_NewsPush_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportantNews); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_NewsPush_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_NewsPush_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_NewsPush_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_NewsPush_proto_goTypes,
		DependencyIndexes: file_pb_NewsPush_proto_depIdxs,
		MessageInfos:      file_pb_NewsPush_proto_msgTypes,
	}.Build()
	File_pb_NewsPush_proto = out.File
	file_pb_NewsPush_proto_rawDesc = nil
	file_pb_NewsPush_proto_goTypes = nil
	file_pb_NewsPush_proto_depIdxs = nil
}
